apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "vidtag.fullname" . }}-config
  labels:
    {{- include "vidtag.labels" . | nindent 4 }}
data:
  SPRING_DATA_REDIS_HOST: "{{ include "vidtag.fullname" . }}-redis"
  SPRING_DATA_REDIS_PORT: "6379"
  {{- if .Values.spring.profiles }}
  SPRING_PROFILES_ACTIVE: {{ .Values.spring.profiles | quote }}
  {{- end }}
