apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "vidtag.fullname" . }}-redis
  labels:
    {{- include "vidtag.labels" . | nindent 4 }}
    {{- include "vidtag.redisSelectorLabels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "vidtag.redisSelectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "vidtag.labels" . | nindent 8 }}
        {{- include "vidtag.redisSelectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: redis
          image: "{{ .Values.redis.image.repository }}:{{ .Values.redis.image.tag }}"
          ports:
            - containerPort: 6379
          readinessProbe:
            exec:
              command:
                - redis-cli
                - ping
            periodSeconds: 5
          volumeMounts:
            - name: redis-data
              mountPath: /data
      volumes:
        - name: redis-data
          emptyDir: {}
